/*
* Groovy script generated by cache explorer memory modelling module. 
*/
import com.tensilica.xide.script.launch.core.launchwrapper.ISSProfiler
import com.tensilica.xide.script.launch.core.launchwrapper.ScriptLaunchConfiguration

ScriptLaunchConfiguration launchConfig = new ScriptLaunchConfiguration();

ISSProfiler runner = new ISSProfiler()
runner.enableParallel(true)


launchConfig.enableMemPerformanceModeling(true);
launchConfig.overrideXpgDCacheSettings(true);
launchConfig.overrideXpgICacheSettings(true);

// Setting memory modelling parameters for config: Cache_cfg_0 

launchConfig.setICacheAssociativity(4);
launchConfig.setICacheLineSize(256);
launchConfig.setICacheSize(65536);
launchConfig.setDCacheAssociativity(1);
launchConfig.setDCacheLineSize(16);
launchConfig.setDCacheSize(1024);
launchConfig.setMemoryWaitstatesRead(10);
launchConfig.setMemoryWaitstatesWrite(10);
launchConfig.setRepeatBlockWaitstatesRead(10);
launchConfig.setRepeatBlockWaitstatesWrite(10);
runner.setDescription(launchConfig,"This profile data set has been generated by the Cache Explorer Module.");

runner.addLaunch(launchConfig,"Cache_cfg_0");
runner.submit();
